/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationIndexRouteImport } from './routes/organization/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as OrganizationSelectOrganizationIndexRouteImport } from './routes/organization/select-organization/index'
import { Route as OrganizationCreateIndexRouteImport } from './routes/organization/create/index'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppMembersIndexRouteImport } from './routes/_app/members/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppTeamsTeamIdRouteImport } from './routes/_app/teams/$teamId'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app/settings/security'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app/settings/general'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppSettingsRolesIndexRouteImport } from './routes/_app/settings/roles/index'
import { Route as AppSettingsRolesNewRouteImport } from './routes/_app/settings/roles/new'
import { Route as AppSettingsRolesRoleIdRouteImport } from './routes/_app/settings/roles/$roleId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/auth/email-verification',
  path: '/auth/email-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const OrganizationSelectOrganizationIndexRoute =
  OrganizationSelectOrganizationIndexRouteImport.update({
    id: '/organization/select-organization/',
    path: '/organization/select-organization/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationCreateIndexRoute = OrganizationCreateIndexRouteImport.update({
  id: '/organization/create/',
  path: '/organization/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesIndexRoute = AppSettingsRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsRolesNewRoute = AppSettingsRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsRolesRoleIdRoute = AppSettingsRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/organization/': typeof OrganizationIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/calendar/': typeof AppCalendarIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/members/': typeof AppMembersIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/teams/': typeof AppTeamsIndexRoute
  '/organization/create/': typeof OrganizationCreateIndexRoute
  '/organization/select-organization/': typeof OrganizationSelectOrganizationIndexRoute
  '/settings/roles/$roleId': typeof AppSettingsRolesRoleIdRoute
  '/settings/roles/new': typeof AppSettingsRolesNewRoute
  '/settings/roles/': typeof AppSettingsRolesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/organization': typeof OrganizationIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/members': typeof AppMembersIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/teams': typeof AppTeamsIndexRoute
  '/organization/create': typeof OrganizationCreateIndexRoute
  '/organization/select-organization': typeof OrganizationSelectOrganizationIndexRoute
  '/settings/roles/$roleId': typeof AppSettingsRolesRoleIdRoute
  '/settings/roles/new': typeof AppSettingsRolesNewRoute
  '/settings/roles': typeof AppSettingsRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/organization/': typeof OrganizationIndexRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/settings/general': typeof AppSettingsGeneralRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/members/': typeof AppMembersIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
  '/organization/create/': typeof OrganizationCreateIndexRoute
  '/organization/select-organization/': typeof OrganizationSelectOrganizationIndexRoute
  '/_app/settings/roles/$roleId': typeof AppSettingsRolesRoleIdRoute
  '/_app/settings/roles/new': typeof AppSettingsRolesNewRoute
  '/_app/settings/roles/': typeof AppSettingsRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/organization/'
    | '/projects/$projectId'
    | '/settings/general'
    | '/settings/profile'
    | '/settings/security'
    | '/teams/$teamId'
    | '/calendar/'
    | '/dashboard/'
    | '/members/'
    | '/projects/'
    | '/reports/'
    | '/settings/'
    | '/tasks/'
    | '/teams/'
    | '/organization/create/'
    | '/organization/select-organization/'
    | '/settings/roles/$roleId'
    | '/settings/roles/new'
    | '/settings/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/organization'
    | '/projects/$projectId'
    | '/settings/general'
    | '/settings/profile'
    | '/settings/security'
    | '/teams/$teamId'
    | '/calendar'
    | '/dashboard'
    | '/members'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/teams'
    | '/organization/create'
    | '/organization/select-organization'
    | '/settings/roles/$roleId'
    | '/settings/roles/new'
    | '/settings/roles'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/settings'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/organization/'
    | '/_app/projects/$projectId'
    | '/_app/settings/general'
    | '/_app/settings/profile'
    | '/_app/settings/security'
    | '/_app/teams/$teamId'
    | '/_app/calendar/'
    | '/_app/dashboard/'
    | '/_app/members/'
    | '/_app/projects/'
    | '/_app/reports/'
    | '/_app/settings/'
    | '/_app/tasks/'
    | '/_app/teams/'
    | '/organization/create/'
    | '/organization/select-organization/'
    | '/_app/settings/roles/$roleId'
    | '/_app/settings/roles/new'
    | '/_app/settings/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
  OrganizationCreateIndexRoute: typeof OrganizationCreateIndexRoute
  OrganizationSelectOrganizationIndexRoute: typeof OrganizationSelectOrganizationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/organization'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/auth/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/organization/select-organization/': {
      id: '/organization/select-organization/'
      path: '/organization/select-organization'
      fullPath: '/organization/select-organization/'
      preLoaderRoute: typeof OrganizationSelectOrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/create/': {
      id: '/organization/create/'
      path: '/organization/create'
      fullPath: '/organization/create/'
      preLoaderRoute: typeof OrganizationCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/': {
      id: '/_app/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId': {
      id: '/_app/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/roles/': {
      id: '/_app/settings/roles/'
      path: '/roles'
      fullPath: '/settings/roles/'
      preLoaderRoute: typeof AppSettingsRolesIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/roles/new': {
      id: '/_app/settings/roles/new'
      path: '/roles/new'
      fullPath: '/settings/roles/new'
      preLoaderRoute: typeof AppSettingsRolesNewRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/roles/$roleId': {
      id: '/_app/settings/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/settings/roles/$roleId'
      preLoaderRoute: typeof AppSettingsRolesRoleIdRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsRolesRoleIdRoute: typeof AppSettingsRolesRoleIdRoute
  AppSettingsRolesNewRoute: typeof AppSettingsRolesNewRoute
  AppSettingsRolesIndexRoute: typeof AppSettingsRolesIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsRolesRoleIdRoute: AppSettingsRolesRoleIdRoute,
  AppSettingsRolesNewRoute: AppSettingsRolesNewRoute,
  AppSettingsRolesIndexRoute: AppSettingsRolesIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppTeamsTeamIdRoute: AppTeamsTeamIdRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
  OrganizationCreateIndexRoute: OrganizationCreateIndexRoute,
  OrganizationSelectOrganizationIndexRoute:
    OrganizationSelectOrganizationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
